export const NEW_COMMENT= 'NEW_COMMENT';
export const SAVE_COMMENT = 'SAVE_COMMENT';
export const FETCH_COMMENT= 'FETCH_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const DELETE_COMMENT= 'DELETE_COMMENT';
export const VOTE_COMMENT = 'VOTE_COMMENT';
export const FULFILLED = '_FULFILLED';